name: Trigger Job Import

on:
  schedule:
    - cron: '0 * * 1 *'  # Every Monday at midnight (00:00)
  workflow_dispatch:  # Allow manual triggering

jobs:
  trigger-import:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Import
        run: |
          echo "Triggering job import at $(date)"
          curl -X POST ${{ secrets.BACKEND_URL }}/api/import/trigger \
            -H "Content-Type: application/json" \
            -d '{"manual": true}' \
            --max-time 30 \
            --retry 3 \
            --retry-delay 5
          
          if [ $? -eq 0 ]; then
            echo "Import triggered successfully"
          else
            echo "Failed to trigger import"
            exit 1
          fi 